name: 'Twinpack Upload'
description: 'Uploads TwinCAT .library files as packages to Twinpack'
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  username:
    description: 'Username for Twinpack'
    required: true
    default: ''
  password:
    description: 'Password for Twinpack'
    required: true
    default: ''
  path:
    description: 'Path where libraries are located'
    required: false
    default: '.'    
  configuration:
    description: ''
    required: false
    default: 'Release'    
  target:
    description: ''
    required: false
    default: 'TC3.1'    
  branch:
    description: ''
    required: false
    default: 'main'    
runs:
  using: "composite"
  steps:
    - run: |
        curl.exe -s -o twinpack-latest.tar.gz https://zeugwerk.dev/Tools/twinpack-latest.tar.gz
        tar -xf twinpack-latest.tar.gz
        ./twinpack.exe push --username "${{ inputs.username }}" --password "${{ inputs.password }}" --without-config --library-path  ${{ inputs.path }} \
                            --configuration ${{ inputs.configuration}} \
                            --target ${{ inputs.target }} \
                            --branch ${{ inputs.branch }} \
                            --skip-duplicate
      shell: bash
